stages:
  - build
  - package
  - deploy

.centos:
  tags: [linux, docker]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/auto/ci/centos:latest

.windows:
  tags: [windows, docker]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/auto/ci/windows:latest-devel
  before_script:
    - . $Profile.AllUsersAllHosts

.release: &release
  CMAKE_BUILD_TYPE: Release

.pylon: &pylon
  WITH_PYLON: 1

.build: &build
  stage: build
  artifacts:
    paths:
      - vendor
      - build
    expire_in: 1 day
  script:
    - ./ci/prepare.py
    - ./ci/configure.py
    - ./ci/compile.py

.package: &package
  stage: package
  artifacts:
    paths:
      - build/*.AppImage
      - build/*.msi
    expire_in: 1 week
  script:
    - ./ci/package.py

"build: [centos]":
  extends: .centos
  <<: *build
  variables:
    <<: [*release]

"build [pylon]: [centos]":
  extends: .centos
  <<: *build
  variables:
    <<: [*release, *pylon]

"build: [windows]":
  extends: .windows
  <<: *build
  variables:
    <<: [*release]

"build [pylon]: [windows]":
  extends: .windows
  <<: *build
  variables:
    <<: [*release, *pylon]

"package: [centos]":
  extends: .centos
  dependencies:
    - "build: [centos]"
  <<: *package

"package [pylon]: [centos]":
  extends: .centos
  dependencies:
    - "build [pylon]: [centos]"
  variables:
    <<: [*pylon]
  <<: *package

"package: [windows]":
  extends: .windows
  dependencies:
    - "build: [windows]"
  <<: *package

"package [pylon]: [windows]":
  extends: .windows
  dependencies:
    - "build [pylon]: [windows]"
  <<: *package
