stages:
  - build
  - package
  - deploy

.centos-7:
  tags: [ linux, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:centos-7

.windows-1809:
  tags: [ windows-1809, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-windows1809


.gcc8: &gcc8
  CC: gcc-8
  CXX: g++-8

.msvc15.9: &msvc15_9
  VCVARS_VER: '14.16'

.release: &release
  CMAKE_BUILD_TYPE: Release

.debug: &debug
  CMAKE_BUILD_TYPE: Debug

.pylon: &pylon
  WITH_PYLON: 1


.build: &build
  stage: build
  artifacts:
    paths:
      - vendor
      - build
    expire_in: 1 day
  script: ./.gitlab-ci.py build

build centos-7:
  extends: .centos-7
  <<: *build
  variables:
    <<: [ *release ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package centos-7'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package centos-7'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package centos-7'

build centos-7[pylon]:
  extends: .centos-7
  <<: *build
  variables:
    <<: [ *release, *pylon ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package centos-7'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package centos-7'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package centos-7'

build windows-1809:
  extends: .windows-1809
  <<: *build
  variables:
    <<: [ *msvc15_9, *release ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package windows-1809'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package windows-1809'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package windows-1809'
    - $env:INSTALL_SHARED_LIBRARIES = 'zlib1;tiff;jpeg62;libpng16;lzma;openblas;boost_system-vc141-mt-x64-1_70;boost_filesystem-vc141-mt-x64-1_70;boost_program_options-vc141-mt-x64-1_70'
    - $env:INSTALL_OPENCV_COMPONENTS = 'core;calib3d;features2d;flann;highgui;imgcodecs;imgproc;ml;objdetect;photo;shape;stitching;superres;video;videoio;videostab;ffmpeg'

build windows-1809[pylon]:
  extends: .windows-1809
  <<: *build
  variables:
    <<: [ *msvc15_9, *release, *pylon ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package windows-1809'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package windows-1809'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package windows-1809'
    - $env:INSTALL_SHARED_LIBRARIES = 'zlib1;tiff;jpeg62;libpng16;lzma;openblas;boost_system-vc141-mt-x64-1_70;boost_filesystem-vc141-mt-x64-1_70;boost_program_options-vc141-mt-x64-1_70'
    - $env:INSTALL_OPENCV_COMPONENTS = 'core;calib3d;features2d;flann;highgui;imgcodecs;imgproc;ml;objdetect;photo;shape;stitching;superres;video;videoio;videostab;ffmpeg'


.package: &package
  stage: package
  artifacts:
    paths:
      - build/*.AppImage
      - build/*.msi
    expire_in: 1 week
  script: ./.gitlab-ci.py package

package centos-7:
  extends: .centos-7
  dependencies:
    - build centos-7
  <<: *package

package centos-7[pylon]:
  extends: .centos-7
  dependencies:
    - build centos-7[pylon]
  <<: *package

package windows-1809:
  extends: .windows-1809
  dependencies:
    - build windows-1809
  <<: *package

package windows-1809[pylon]:
  extends: .windows-1809
  dependencies:
    - build windows-1809[pylon]
  <<: *package
