stages:
  - build
  - package
  - deploy

.ubuntu-18.04:
  tags: [ linux, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-ubuntu18.04

.windows-1809:
  tags: [ windows-1809, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-windows1809


.gcc8: &gcc8
  CC: gcc-8
  CXX: g++-8

.msvc15.9: &msvc15_9
  VCVARS_VER: '14.16'

.release: &release
  CMAKE_BUILD_TYPE: Release

.debug: &debug
  CMAKE_BUILD_TYPE: Debug

.pylon5: &pylon5
  WITH_PYLON5: 1


.build: &build
  stage: build
  artifacts:
    paths:
      - vendor
      - build
    expire_in: 1 day
  script: ./.gitlab-ci.py build

build ubuntu-18.04:
  extends: .ubuntu-18.04
  <<: *build
  variables:
    <<: [ *gcc8, *release ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package ubuntu-18.04'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package ubuntu-18.04'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package ubuntu-18.04'

build windows-1809:
  extends: .windows-1809
  <<: *build
  variables:
    <<: [ *msvc15_9, *release ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package windows-1809'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package windows-1809'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package windows-1809'
    - $env:INSTALL_SHARED_LIBRARIES = 'zlib1;tiff;jpeg62;libpng16;lzma;openblas;boost_system-vc141-mt-x64-1_68;boost_filesystem-vc141-mt-x64-1_68;boost_program_options-vc141-mt-x64-1_68'
    - $env:INSTALL_OPENCV_COMPONENTS = 'core;calib3d;features2d;flann;highgui;imgcodecs;imgproc;ml;objdetect;photo;shape;stitching;superres;video;videoio;videostab;ffmpeg'

build windows-1809[pylon5]:
  extends: .windows-1809
  <<: *build
  variables:
    <<: [ *msvc15_9, *release, *pylon5 ]
  before_script:
    - ./.gitlab-ci.py prepare
      --dependency biotracker-interfaces    bioroboticslab/biotracker/interfaces      master 'package windows-1809'
      --dependency biotracker-utility       bioroboticslab/biotracker/utility         master 'package windows-1809'
      --dependency robofish-behavior_loader bioroboticslab/biotracker/behavior_loader master 'package windows-1809'
    - $env:INSTALL_SHARED_LIBRARIES = 'zlib1;tiff;jpeg62;libpng16;lzma;openblas;boost_system-vc141-mt-x64-1_68;boost_filesystem-vc141-mt-x64-1_68;boost_program_options-vc141-mt-x64-1_68'
    - $env:INSTALL_OPENCV_COMPONENTS = 'core;calib3d;features2d;flann;highgui;imgcodecs;imgproc;ml;objdetect;photo;shape;stitching;superres;video;videoio;videostab;ffmpeg'


.package: &package
  stage: package
  artifacts:
    paths:
      - build/*.AppImage
      - build/*.msi
    expire_in: 1 week
  script: ./.gitlab-ci.py package

package ubuntu-18.04:
  extends: .ubuntu-18.04
  dependencies:
    - build ubuntu-18.04
  <<: *package
  tags: [ linux, docker_privileged ]

package windows-1809:
  extends: .windows-1809
  dependencies:
    - build windows-1809
  <<: *package

package windows-1809[pylon5]:
  extends: .windows-1809
  dependencies:
    - build windows-1809[pylon5]
  <<: *package
